#!/usr/bin/env node

/**
 * Setup Environment Variables
 * Creates .env file with default production API URL
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const envExamplePath = path.join(__dirname, '.env.example');

const envContent = `# API Configuration
# Generated by setup-env.js
# Update these values as needed

# Production API URL (default)
REACT_APP_API_URL=https://studyspot-api.onrender.com
REACT_APP_AUTH_URL=https://studyspot-api.onrender.com

# For local development, uncomment and use:
# REACT_APP_API_URL=http://localhost:3001
# REACT_APP_AUTH_URL=http://localhost:3001

# Environment
REACT_APP_ENVIRONMENT=development

# Debug mode (optional)
# REACT_APP_DEBUG=false
`;

try {
  if (fs.existsSync(envPath)) {
    console.log('✅ .env file already exists');
    console.log('📝 Current .env file location:', envPath);
    console.log('💡 To update it, edit the file manually or delete it and run this script again');
  } else {
    fs.writeFileSync(envPath, envContent, 'utf8');
    console.log('✅ .env file created successfully!');
    console.log('📝 File location:', envPath);
    console.log('🔧 API URL:', 'https://studyspot-api.onrender.com');
    console.log('💡 To use local backend, edit .env and change REACT_APP_API_URL to http://localhost:3001');
  }
} catch (error) {
  console.error('❌ Error creating .env file:', error.message);
  process.exit(1);
}

