apiVersion: v1
kind: ServiceAccount
metadata:
  name: studyspot-sa
  namespace: studyspot
  labels:
    app.kubernetes.io/name: studyspot-enterprise
    app.kubernetes.io/version: "1.0.0"
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: studyspot
  name: studyspot-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studyspot-rolebinding
  namespace: studyspot
subjects:
- kind: ServiceAccount
  name: studyspot-sa
  namespace: studyspot
roleRef:
  kind: Role
  name: studyspot-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: studyspot-network-policy
  namespace: studyspot
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: studyspot-enterprise
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: studyspot
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3005
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 3007
    - protocol: TCP
      port: 3008
    - protocol: TCP
      port: 3009
    - protocol: TCP
      port: 3014
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: studyspot
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 9092
    - protocol: TCP
      port: 9200
    - protocol: TCP
      port: 27017
    - protocol: TCP
      port: 8086
    - protocol: TCP
      port: 5672
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
    - protocol: UDP
      port: 53

---
apiVersion: v1
kind: PodSecurityPolicy
metadata:
  name: studyspot-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: studyspot-pdb
  namespace: studyspot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: studyspot-enterprise
