apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: studyspot-enterprise-base
  namespace: studyspot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - network-policy.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: studyspot-enterprise
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: studyspot-platform

commonAnnotations:
  studyspot.com/created-by: "StudySpot Enterprise Platform"
  studyspot.com/version: "1.0.0"
  studyspot.com/environment: "production"

patchesStrategicMerge:
  - patches/security-patch.yaml
  - patches/monitoring-patch.yaml
  - patches/logging-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis-service:6379
      - DATABASE_URL=postgresql://postgres:5432/studyspot
      - KAFKA_HOST=kafka-service:9092
      - ELASTICSEARCH_HOST=elasticsearch-service:9200
      - MONGODB_URL=mongodb://mongodb-service:27017
      - INFLUXDB_HOST=influxdb-service:8086
      - RABBITMQ_URL=amqp://rabbitmq-service:5672
    files:
      - config/app.properties
      - config/logging.yaml
      - config/monitoring.yaml

secretGenerator:
  - name: app-secrets
    literals:
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - DATABASE_PASSWORD=your-database-password
      - REDIS_PASSWORD=your-redis-password
      - SMTP_USER=your-smtp-user
      - SMTP_PASS=your-smtp-password
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - OPENAI_API_KEY=your-openai-api-key
      - GOOGLE_CLOUD_PROJECT_ID=your-google-cloud-project-id
      - AWS_ACCESS_KEY_ID=your-aws-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key
    type: Opaque

images:
  - name: studyspot/api-gateway
    newTag: "1.0.0"
  - name: studyspot/crm-service
    newTag: "1.0.0"
  - name: studyspot/communication-service
    newTag: "1.0.0"
  - name: studyspot/ml-service
    newTag: "1.0.0"
  - name: studyspot/analytics-service
    newTag: "1.0.0"
  - name: studyspot/ai-service
    newTag: "1.0.0"
  - name: studyspot/data-pipeline
    newTag: "1.0.0"
  - name: studyspot/web-owner
    newTag: "1.0.0"
  - name: studyspot/web-admin
    newTag: "1.0.0"
  - name: studyspot/mobile
    newTag: "1.0.0"

replicas:
  - name: api-gateway
    count: 3
  - name: crm-service
    count: 2
  - name: communication-service
    count: 2
  - name: ml-service
    count: 2
  - name: analytics-service
    count: 2
  - name: ai-service
    count: 2
  - name: data-pipeline
    count: 1
  - name: web-owner
    count: 2
  - name: web-admin
    count: 2
