// Reports & Export Page
import React, { useState } from 'react';
import { Box, Typography, Card, CardContent, Button, Chip, GridLegacy as Grid, FormControl, InputLabel, Select, MenuItem, TextField } from '@mui/material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { Description, GetApp, PictureAsPdf, TableChart, Email, Schedule } from '@mui/icons-material';

const ReportsPage: React.FC = () => {
  const reports = [
    { id: 1, name: 'Monthly Revenue Report', type: 'Revenue', format: 'PDF', generated: '2025-10-31', generatedBy: 'Admin', size: '2.4 MB', status: 'Ready' },
    { id: 2, name: 'User Activity Report', type: 'Analytics', format: 'Excel', generated: '2025-10-30', generatedBy: 'Amit', size: '1.8 MB', status: 'Ready' },
    { id: 3, name: 'Subscription Summary', type: 'Subscription', format: 'CSV', generated: '2025-10-29', generatedBy: 'Sneha', size: '450 KB', status: 'Ready' },
    { id: 4, name: 'Payment Transactions', type: 'Payment', format: 'PDF', generated: '2025-10-28', generatedBy: 'Admin', size: '3.1 MB', status: 'Ready' },
    { id: 5, name: 'Tenant Performance', type: 'Tenant', format: 'Excel', generated: '2025-10-27', generatedBy: 'Rahul', size: '2.2 MB', status: 'Ready' },
  ];

  const columns: GridColDef[] = [
    { field: 'name', headerName: 'Report Name', width: 250 },
    { field: 'type', headerName: 'Type', width: 150, renderCell: (params) => <Chip label={params.value} color="primary" size="small" /> },
    { field: 'format', headerName: 'Format', width: 100, renderCell: (params) => <Chip label={params.value} size="small" variant="outlined" /> },
    { field: 'generated', headerName: 'Generated', width: 120 },
    { field: 'generatedBy', headerName: 'Generated By', width: 140 },
    { field: 'size', headerName: 'Size', width: 100 },
    { field: 'status', headerName: 'Status', width: 110, renderCell: (params) => <Chip label={params.value} color="success" size="small" /> },
    { field: 'actions', headerName: 'Actions', width: 150, renderCell: () => (
      <Button size="small" variant="contained" startIcon={<GetApp />}>Download</Button>
    )},
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" fontWeight="bold" gutterBottom>Reports & Export</Typography>
        <Typography variant="body2" color="text.secondary">Generate and download comprehensive reports</Typography>
      </Box>

      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Card><CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 1 }}>
              <Description color="primary" sx={{ mr: 1 }} />
              <Typography variant="body2" color="text.secondary">Total Reports</Typography>
            </Box>
            <Typography variant="h4" fontWeight="bold">5</Typography>
          </CardContent></Card>
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <Card><CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 1 }}>
              <Schedule color="warning" sx={{ mr: 1 }} />
              <Typography variant="body2" color="text.secondary">Scheduled Reports</Typography>
            </Box>
            <Typography variant="h4" fontWeight="bold">3</Typography>
          </CardContent></Card>
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <Card><CardContent>
            <Typography variant="body2" color="text.secondary">Reports This Month</Typography>
            <Typography variant="h4" fontWeight="bold">12</Typography>
          </CardContent></Card>
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <Card><CardContent>
            <Typography variant="body2" color="text.secondary">Total Size</Typography>
            <Typography variant="h4" fontWeight="bold">10.9 MB</Typography>
          </CardContent></Card>
        </Grid>
      </Grid>

      <Card sx={{ mb: 3 }}><CardContent>
        <Typography variant="h6" fontWeight="bold" gutterBottom>Generate New Report</Typography>
        <Grid container spacing={2}>
          <Grid item xs={12} md={3}>
            <FormControl fullWidth>
              <InputLabel>Report Type</InputLabel>
              <Select label="Report Type">
                <MenuItem value="revenue">Revenue Report</MenuItem>
                <MenuItem value="user">User Activity Report</MenuItem>
                <MenuItem value="subscription">Subscription Report</MenuItem>
                <MenuItem value="payment">Payment Report</MenuItem>
                <MenuItem value="tenant">Tenant Report</MenuItem>
                <MenuItem value="custom">Custom Report</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} md={3}>
            <TextField fullWidth label="From Date" type="date" InputLabelProps={{ shrink: true }} />
          </Grid>
          <Grid item xs={12} md={3}>
            <TextField fullWidth label="To Date" type="date" InputLabelProps={{ shrink: true }} />
          </Grid>
          <Grid item xs={12} md={3}>
            <FormControl fullWidth>
              <InputLabel>Format</InputLabel>
              <Select label="Format" defaultValue="PDF">
                <MenuItem value="PDF">PDF</MenuItem>
                <MenuItem value="Excel">Excel</MenuItem>
                <MenuItem value="CSV">CSV</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12}>
            <Button variant="contained" startIcon={<Description />} sx={{ mr: 2 }}>Generate Report</Button>
            <Button variant="outlined" startIcon={<Email />}>Email Report</Button>
          </Grid>
        </Grid>
      </CardContent></Card>

      <Card><CardContent>
        <Typography variant="h6" fontWeight="bold" gutterBottom>Generated Reports</Typography>
        <DataGrid rows={reports} columns={columns} autoHeight pageSizeOptions={[10, 25, 50]} initialState={{ pagination: { paginationModel: { pageSize: 10 }}}} checkboxSelection />
      </CardContent></Card>
    </Box>
  );
};

export default ReportsPage;

